---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-3
  name: nginx-3
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginx-3
  type: ClusterIP
