apiVersion: v1
kind: ConfigMap
metadata:
  name: index-2
data:
  index.html: |
    <html>
    <h1>Welcome</h1>
    </br>
    <h1>Hello from server 2</h1>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-2
  name: nginx-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-2
  template:
    metadata:
      labels:
        app: nginx-2
    spec:
      containers:
      - image: nginxinc/nginx-unprivileged:stable-alpine
        imagePullPolicy: IfNotPresent
        name: nginx-2
        ports:
        - containerPort: 8080
          name: web
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
            - name: index-2
              mountPath: /usr/share/nginx/html/
      volumes:
      - name: index-2
        configMap:
          name: index-2

      terminationGracePeriodSeconds: 30
