---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-1
  name: nginx-1
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginx-1
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-2
  name: nginx-2
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginx-2
  type: ClusterIP
